### ISSUE TITLE
Testes unitários e Storybook

### ISSUE THREAD

**Issue by rafaelcanovas** [lucasReghiniM/AllTheAnime#1]
Boa noite Lucas,

Como você abordaria a questão de testes unitários de componentes?

Você tem experiência com Storybook? Acreditamos que o Storybook é uma grande ferramenta de produtividade, auxiliando na consistência e na testagem ao vivo dos componentes escritos.

Abs.

**Comment by lucasReghiniM** [comment]
Na questão de testes automatizados utilizo Jest ou testing library.
Ja Storybook conheço mas não cheguei a utilizar, porem ja criei libs de UI kit com o create-react-library.

**Comment by rafaelcanovas** [comment]
Obrigado Lucas!
