### ISSUE TITLE
Estado global

### ISSUE THREAD

**Issue by rafaelcanovas** [lucasReghiniM/AllTheAnime#2]
Boa noite Lucas,

Acredito que o gerenciamento de variáveis de estado global numa aplicação de pequeno porte, como essa, seja um overkill. No entanto à medida que a aplicação vai crescendo e coisas com autenticação vão surgindo, é necessário o gerenciamento de variáveis de estado global.

Como você abordaria isso?

Abs.

**Comment by lucasReghiniM** [comment]
Bom dia.
Para questões de gerenciamento de estado utilizo duas abordagens.
Para aplicações que exigem transmissão de objetos e informações eu utilizo o context API, assim evitando problemas como prop drilling.
Já para aplicações mais complexas, que exigem gerenciamento de estados, rastreamento de atualizações, persistência de dados, manutenção de chamadas assíncronas, middlewares e logicas mais complexas eu utilizo o Redux e suas tecnologias.

**Comment by rafaelcanovas** [comment]
Obrigado Lucas!
